const papersData = [
  // ===== 2025年 =====
  {
    id: "wan",
    title: "Wan: Open and Advanced Large-Scale Video Generative Models",
    titleJa: "Wan：オープンソース大規模動画生成モデル",
    authors: "Wan Team, Alibaba Group",
    year: 2025,
    venue: "arXiv 2025",
    tags: ["動画生成", "拡散モデル", "生成AI"],
    summary: "本論文では、Wan と呼ばれるオープンソースの大規模動画生成モデルシリーズを紹介する。Wan は、テキストから動画・画像から動画・動画編集など幅広いタスクに対応しており、動画生成の品質・使いやすさ・学習効率のすべてにおいて既存手法を大幅に上回ることを目指して設計された。Flow Matching に基づく拡散 Transformer（DiT）アーキテクチャを中核とし、3D因果 VAE によって時空間情報を圧縮した潜在空間上で学習が行われる。独自に構築した大規模動画データセットと段階的な学習パイプラインにより、Sora に代表されるクローズドモデルと比肩する生成品質を達成した。VBench・EvalCrafter 等の動画品質ベンチマークにおいて既存のオープンソースモデルを上回るスコアを示している。モデルウェイト・学習コード・データ処理ツールをすべてオープンで公開することで、コミュニティによる再現・改良を可能にした点も本研究の重要な貢献である。",
    background: "Soraの登場以降、動画生成の品質競争が激化したが、大半の高品質モデルはクローズドソースであり研究コミュニティが自由に使える強力な動画生成基盤が不足していた。",
    method: "DiTバックボーンに3D注意機構を組み込み、テキスト・画像・動画の各条件付け入力をクロスアテンションで統合。VAEで動画を圧縮した潜在空間上でFlow Matchingを用いた拡散学習を行う。",
    results: "EvalCrafter・VBench等の動画品質ベンチマークで既存オープンソースモデルを大幅に上回り、クローズドモデルと同水準のスコアを達成。長尺動画（最大5秒）でも時間的一貫性を維持した。",
    discussion: "動画生成のオープンソース化において大きな一歩であり、動画理解・ロボット学習・映像制作など様々な応用の基盤となることが期待される。",
    links: { arxiv: "https://arxiv.org/abs/2503.20314", github: "https://github.com/Wan-Video/Wan2.1" }
  },
  {
    id: "cosmos",
    title: "Cosmos World Foundation Model Platform for Physical AI",
    titleJa: "Cosmos：物理AIのための世界基盤モデルプラットフォーム（NVIDIA）",
    authors: "NVIDIA Research",
    year: 2025,
    venue: "arXiv 2025",
    tags: ["動画生成", "世界モデル", "Physical AI"],
    summary: "本論文では、物理 AI（ロボット・自動運転など）の開発・評価を加速するための世界基盤モデル（World Foundation Model, WFM）プラットフォーム Cosmos を提案する。Cosmos は、現実世界の物理法則を遵守したビデオを生成する能力を持ち、実世界データの収集コストが高い物理 AI の訓練において合成データを補完する役割を担う。連続ビデオトークナイザ（DVT/CVT）によって動画を効率的に潜在空間へ圧縮し、その上でオートレグレッシブ型または拡散/フローマッチング型のトランスフォーマーが生成を行う二段構成を採用する。テキスト・画像・動画など複数のモダリティを条件付け入力として受け付け、物理整合性を高めるための専用ポストトレーニングパイプラインも提供する。自動運転・ロボット操作シーンの生成実験において、生成データで追加訓練することで実世界タスクの性能が向上することを実証した。モデルウェイトをオープンウェイトで公開し、物理 AI 研究コミュニティへの貢献を意図している。",
    background: "物理AIシステム（自動運転・ロボット）の訓練には大量の実世界データが必要だが収集コストが高い。リアルなシミュレーションが代替手段として有望視されていたが、従来の3Dシミュレータはリアリズムに限界があった。",
    method: "連続ビデオトークナイザ（DVT/CVT）で動画を圧縮後、オートレグレッシブまたは拡散/フローマッチング型トランスフォーマーで生成。物理整合性を高めるための専用Fine-tuningパイプラインを提供する。",
    results: "自動運転シーン・ロボット操作シーンの生成品質で既存Video生成モデルを上回り、生成データでの追加訓練により実世界タスクの性能が向上することを実験で確認。",
    discussion: "世界モデルとロボット・自動運転技術の融合という方向性を示す重要な研究。オープンウェイトで提供されており、物理AI研究コミュニティへの影響が大きい。",
    links: { arxiv: "https://arxiv.org/abs/2501.03575", github: "https://github.com/nvidia-research/cosmos" }
  },
  {
    id: "sam2",
    title: "SAM 2: Segment Anything in Images and Videos",
    titleJa: "SAM 2：画像と動画を横断するあらゆるもののセグメンテーション",
    authors: "Nikhila Ravi, Valentin Gabeur, Yuan-Ting Hu, Ronghang Hu, Chaitanya Ryali, Tengyu Ma, Haitham Khedr, Roman Rädle, Chloe Rolland, Laura Gustafson, Eric Mintun, Junting Pan, Kalyan Vasudev Alwala, Nicolas Carion, Chao-Yuan Wu, Ross Girshick, Piotr Dollár, Christoph Feichtenhofer",
    year: 2024,
    venue: "ICLR 2025",
    tags: ["セグメンテーション", "動画", "Foundation Model"],
    summary: "本論文では、静止画と動画の両方においてあらゆる物体をセグメンテーションできる汎用モデル SAM 2 を提案する。SAM 2 は、ユーザーが点・ボックス・マスクなどのプロンプトを与えることで、動画中の任意のオブジェクトをリアルタイムに追跡しセグメンテーションするストリーミング型アーキテクチャを採用する。核心となる「メモリモジュール」は、過去フレームのオブジェクト外観をメモリバンクに蓄積し、未来フレームの予測精度を向上させる。本研究ではさらに SA-V データセット（5 万本以上の動画、190 万以上の空間-時間マスク）を新たに構築し、多様なシナリオへのゼロショット汎化を支援した。同データセットと SA-1B（静止画）を組み合わせて学習した結果、ゼロショット設定において既存の動画セグメンテーション手法を大幅に上回る精度を達成し、かつユーザーインタラクション数も大幅に削減できることを示した。",
    background: "SAMは静止画の汎用セグメンテーションで革新をもたらしたが、動画への対応がなかった。動画セグメンテーションは時間的一貫性・オクルージョン処理が難しく、ゼロショットで機能する汎用手法が求められていた。",
    method: "階層型画像エンコーダ・プロンプトエンコーダ・マスクデコーダに加え、メモリエンコーダ・メモリバンク・メモリアテンションモジュールを追加。各フレームのマスクと特徴量を蓄積し時系列で伝搬する。",
    results: "動画オブジェクトセグメンテーション（DAVIS・YouTube-VOS）でゼロショットにもかかわらず教師あり手法に迫る性能。インタラクション数を大幅に削減しながら高精度なアノテーションが可能。",
    discussion: "動画セグメンテーションの汎用基盤として医療・自動運転・映像編集など多分野への応用が期待される。SAMのモデルアーキテクチャを拡張した設計は今後の動画理解研究の参照点となる。",
    links: { arxiv: "https://arxiv.org/abs/2408.00714", github: "https://github.com/facebookresearch/segment-anything-2" }
  },
  {
    id: "depth-anything-v2",
    title: "Depth Anything V2",
    titleJa: "Depth Anything V2：より精密で堅牢な単眼深度推定",
    authors: "Lihe Yang, Bingyi Kang, Zilong Huang, Zhen Zhao, Xiaogang Xu, Jiashi Feng, Hengshuang Zhao",
    year: 2024,
    venue: "NeurIPS 2024",
    tags: ["深度推定", "3D", "Foundation Model"],
    summary: "本論文では、単眼深度推定の汎用基盤モデル Depth Anything V2 を提案する。先代 V1 の主要な問題であった「疎な細部の不正確さ」と「複雑テクスチャ領域での不安定さ」を克服するため、本研究では実世界の粗いラベルを使わず、精密な GT 深度を持つ合成データのみで強力な教師モデルを学習し、次にそのモデルが生成した疑似ラベルを用いて 6,200 万枚の実世界画像で学習する二段階パイプラインを採用した。この手法により、V1 と比較してより細かい深度の詳細・境界の鋭さ・照明変化への耐性が大幅に向上する。DINOv2 をバックボーンとして採用し、Small・Base・Large の 3 スケールを提供する。NYUv2・KITTI・ETH3D を含む複数のベンチマークで現行 SoTA を更新し、ゼロショット汎化においても既存手法を顕著に上回ることを実証した。",
    background: "単眼深度推定はRGBのみから奥行きを推定する困難な問題。V1は実世界ラベルの質のばらつきが性能の上限を制約しており、特に反射面・細い物体・繰り返しテクスチャで精度が低下していた。",
    method: "合成データで精度の高い教師モデルを学習→実世界の大量無ラベル画像に擬似ラベルを付与→DINOv2バックボーンでスケーラブルに学習。affine-invariant lossで絶対スケール不定性に対処する。",
    results: "NYUv2・KITTI・ETH3D等の複数ベンチマークでV1を大幅に上回り、現行SoTAを更新。ゼロショット汎化においてもロバスト性が顕著に改善した。",
    discussion: "合成→実世界という学習パイプラインの設計思想は今後の深度推定・3D復元研究の参考となる。自動運転・AR/VR・ロボティクスへの応用が広い。",
    links: { arxiv: "https://arxiv.org/abs/2406.09414", github: "https://github.com/DepthAnything/Depth-Anything-V2" }
  },
  {
    id: "3dgs",
    title: "3D Gaussian Splatting for Real-Time Radiance Field Rendering",
    titleJa: "3DGS：リアルタイム放射輝度場レンダリングのための3Dガウシアンスプラッティング",
    authors: "Bernhard Kerbl, Georgios Kopanas, Thomas Leimkühler, George Drettakis",
    year: 2023,
    venue: "SIGGRAPH 2023",
    tags: ["3D", "レンダリング", "リアルタイム"],
    summary: "本論文では、3D シーンを多数の 3D ガウシアン（位置・共分散行列・不透明度・色の球面調和関数係数を持つ楕円体）の集合として明示的に表現し、タイルベースのラスタライゼーションによってリアルタイムでノベルビュー合成を実現する手法、3D Gaussian Splatting（3DGS）を提案する。Structure from Motion（SfM）で得た疎な点群を初期化として使用し、学習中に各ガウシアンを微分可能なレンダリングで最適化しながら適応的な密度制御（分割・複製・剪定）を繰り返す。NeRF に代表される暗黙的表現とは異なり、明示的なプリミティブを用いるため高速な GPU ラスタライゼーションに親和性が高い。Tanks and Temples・Deep Blending・Mip-NeRF360 等のベンチマークにおいて、NeRF 系手法と同等以上の PSNR/SSIM を維持しながらレンダリング速度を 30〜160 fps（Instant-NGP 比でも同等以上）に向上させた。",
    background: "NeRFは高品質な3Dシーン再現を達成したが、推論に数秒かかりリアルタイム用途に使えなかった。学習済みモデルをリアルタイムで視点変換しながら表示できる技術が求められていた。",
    method: "3D空間に配置されたガウシアン集合として場面を表現。各ガウシアンの属性を微分可能なレンダリングで勾配降下学習し、タイルベースのCUDAラスタライザで高速描画する。",
    results: "Tanks and Temples・Deep Blending・Mip-NeRF360等のベンチマークでNeRF系手法に匹敵するPSNR/SSIMを達成しながら、レンダリング速度を30〜160fps（NeRF比100倍以上）に向上させた。",
    discussion: "3DGSはNeRFに代わる3D表現のパラダイムとして急速に普及し、VR/AR・映画VFX・自動運転・ロボットマッピングなど幅広い応用が展開されている。編集・動的シーン対応などの拡張研究も急増している。",
    links: { arxiv: "https://arxiv.org/abs/2308.04079", github: "https://github.com/graphdeco-inria/gaussian-splatting" }
  },
  // ===== 生成AI / 拡散モデル =====
  {
    id: "ddpm-beat-gans",
    title: "Diffusion Models Beat GANs on Image Synthesis",
    titleJa: "拡散モデルがGANを超えた：高品質画像合成への道",
    authors: "Prafulla Dhariwal, Alexander Nichol",
    year: 2021,
    venue: "NeurIPS 2021",
    tags: ["生成AI", "拡散モデル", "画像生成"],
    summary: "本論文では、拡散確率モデル（DDPM）が改良された場合に画像合成品質において GAN を上回りうることを示す。改良点は主に 2 つある。第一に、アーキテクチャの改善で、Attention 解像度・チャンネル数・ヘッド数の拡張を行い、ノイズスケジュールのバリアンスを学習可能にした。第二に、クラシファイアガイダンスという手法の導入で、学習済みの分類器の勾配を拡散サンプリングに加えることで多様性と忠実度のトレードオフを制御する。条件なし・条件付きの両設定で ImageNet における FID および Precision/Recall を評価した結果、BigGAN-deep などの最先端 GAN をすべての指標で上回ることを確認した。この結果は、拡散モデルが複雑なデータ分布を高い忠実度でサンプリングする能力を持つことを強く支持するものである。",
    background: "GANは高品質な画像生成において長年SoTAを維持してきたが、学習の不安定性・モード崩壊という固有の問題を抱えていた。拡散モデルは理論的に安定だが、速度と品質でGANに及ばないとされていた。",
    method: "U-NetベースのアーキテクチャにMulti-Head Self-Attentionを追加し、ノイズスケジュールをハイブリッド損失で学習可能にした。さらに事前学習済み分類器からの勾配スケーリングによるクラシファイアガイダンスを導入した。",
    results: "ImageNet 256×256においてFID 4.59（条件付き）を達成し、BigGAN-deepのFID 6.95を大幅に上回った。人間評価でもGAN生成画像より自然と判定される割合が高かった。",
    discussion: "この研究が触媒となり、Stable Diffusion・DALL-E 2など実用的な拡散モデルの研究が一気に加速した。クラシファイアガイダンスはその後CFG（Classifier-Free Guidance）へと発展し、現在の生成モデルの標準技術となっている。",
    links: { arxiv: "https://arxiv.org/abs/2105.05233", github: "https://github.com/openai/guided-diffusion" }
  },
  {
    id: "ldm",
    title: "High-Resolution Image Synthesis with Latent Diffusion Models",
    titleJa: "潜在拡散モデルによる高解像度画像合成（Stable Diffusionの原論文）",
    authors: "Robin Rombach, Andreas Blattmann, Dominik Lorenz, Patrick Esser, Björn Ommer",
    year: 2022,
    venue: "CVPR 2022",
    tags: ["生成AI", "拡散モデル", "潜在空間", "画像生成"],
    summary: "本論文では、画像形成過程を圧縮・生成の 2 段階に分離することで、計算効率を保ちながら高品質・高解像度な画像合成を実現する Latent Diffusion Models（LDM）を提案する。まず強力なエンコーダがピクセル画像を低次元の潜在表現に圧縮し、次に拡散モデルをその潜在空間上で学習させる。これにより、計算コストをピクセル空間の拡散モデルに比べて大幅に削減しながらも、高忠実度のサンプルを生成できる。さらにクロスアテンション機構を導入することで、テキスト・バウンディングボックス・レイアウトなど任意の入力形式での条件付き画像合成が可能となる。非条件生成・テキスト条件付き生成・レイアウト条件付き生成・超解像・インペインティングにわたる実験で、この手法が計算コストと生成品質のトレードオフにおいて優れた領域に位置することを示した。本アーキテクチャは Stable Diffusion として一般公開されている。",
    background: "従来の拡散モデルはピクセル空間で動作するため高解像度画像の学習に莫大なGPUメモリと計算時間が必要だった。この計算コストの高さが実用化の障壁となっていた。",
    method: "VQ-正則化またはKL-正則化付きAutoencoderで画像を潜在空間に圧縮後、その空間でDDPMを適用。クロスアテンションでドメイン固有エンコーダからの条件情報を注入する。",
    results: "CelebA-HQやFFHQ（512×512）などで生成品質・速度ともにPixel-DDPMを大幅に上回った。テキスト条件付き生成（LAION）でもFIDが従来手法比で改善。",
    discussion: "潜在空間拡散という設計思想はその後の研究の標準的なアプローチとなり、画像・動画・3D生成など幅広い分野へ展開されている。コミュニティ主導の発展により研究と産業双方に多大な影響を与えた。",
    links: { arxiv: "https://arxiv.org/abs/2112.10752", github: "https://github.com/CompVis/latent-diffusion" }
  },
  {
    id: "dreambooth",
    title: "DreamBooth: Fine Tuning Text-to-Image Diffusion Models for Subject-Driven Generation",
    titleJa: "DreamBooth：特定被写体に特化したテキスト条件付き画像生成",
    authors: "Nataniel Ruiz, Yuanzhen Li, Varun Jampani, Yael Pritch, Michael Rubinstein, Kfir Aberman",
    year: 2023,
    venue: "CVPR 2023",
    tags: ["生成AI", "拡散モデル", "パーソナライゼーション"],
    summary: "本論文では、事前学習済みのテキストから画像へのDiffusionモデルを「個人化（パーソナライズ）」するための新手法 DreamBooth を提案する。わずか 3〜5 枚の対象被写体（人物・ペット・物体など）の参照画像から、テキスト埋め込み空間内の固有の希少トークン識別子（例：「a [V] dog」）に被写体を関連付け、モデル全体をファインチューニングする。これにより、モデルは被写体の外見を記憶し、任意のテキストプロンプトで指定される多様なシーン・照明・カメラアングル・スタイルの下でその被写体を高忠実度に生成できるようになる。学習中に「事前保存損失（Prior Preservation Loss）」を導入することで、被写体クラス全般の知識が失われる言語ドリフトや過学習を防止する。DINO・CLIP 特徴量を用いた定量評価および人間評価において、Textual Inversion 等の既存手法を大幅に上回る被写体忠実度とテキストアライメントを達成した。",
    background: "テキストから画像を生成するモデルは汎用性が高い一方、「特定の人物の顔」「飼い犬の外見」のような個人固有の概念を忠実に再現することは困難だった。",
    method: "テキスト埋め込み内の希少識別子トークンに被写体を関連付ける。全モデルパラメータを少数の被写体画像でファインチューニングし、Prior Preservation Lossで汎化性を保つ。",
    results: "DINO特徴量・CLIPスコアを用いた定量評価で、テキストアライメントと被写体忠実度の両方において高い値を達成。人間評価でも既存手法（Textual Inversion等）を大幅に上回った。",
    discussion: "LoRAと組み合わせることでパラメータ効率が大幅に改善され、その後個人化・スタイル転写の研究に広く応用されている。プロフィール写真生成や広告素材制作などの商業利用も広がった。",
    links: { arxiv: "https://arxiv.org/abs/2208.12242", github: "https://github.com/google/dreambooth" }
  },
  // ===== 3D / NeRF =====
  {
    id: "nerf",
    title: "NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis",
    titleJa: "NeRF：神経放射場による3Dシーン表現と新規視点合成",
    authors: "Ben Mildenhall, Pratul P. Srinivasan, Matthew Tancik, Jonathan T. Barron, Ravi Ramamoorthi, Ren Ng",
    year: 2020,
    venue: "ECCV 2020",
    tags: ["3D", "NeRF", "新規視点合成"],
    summary: "本論文では、静止した画像の集合から複雑なシーンの連続的な 5D 神経放射場（Neural Radiance Field, NeRF）表現を最適化することで、任意の新規視点から写真品質の合成を行う手法を提案する。シーン内の任意の 3D 点と視線方向を入力とし、体積密度と視線依存の放射輝度を出力する全結合ネットワーク（MLP）でシーンを表現する。カメラレイに沿ったクラシカルなボリュームレンダリングで 2D 画像を合成し、その出力と実画像との差異を損失として逆伝播することで学習が進む。高周波な形状・外観を効率的に表現するための位置エンコーディングと、粗いネットワークと精細なネットワークによる階層的サンプリング戦略の組み合わせが本手法の核心である。複数の合成・実写データセットにおいて、従来手法（SRN, NV, LLFF）を PSNR・SSIM・LPIPS のすべてで大幅に上回ることを示した。",
    background: "新規視点合成は長年3Dグラフィクスの中心課題だったが、明示的な3D幾何（メッシュや点群）の復元を経由する従来法は複雑なシーンに弱く、品質にも限界があった。",
    method: "5次元入力（位置＋方向）に対しFully-connected MLPで色・密度を出力。Positional Encodingで高周波成分を捉えやすくし、Hierarchicalサンプリングで効率的にレイマーチングを行う。",
    results: "Synthetic・Real-world両データセットでPSNR・SSIMが従来の新規視点合成手法（SRN, NV, LLFF等）を大幅に上回った。特に複雑な非ランバート反射と細部再現で優位性を示した。",
    discussion: "NeRFはその後数百本以上の拡張研究（Instant-NGP・Mip-NeRF・NeRF-W・3DGSなど）を生み出し、3D表現の研究分野を根本的に変えた。ARや自動運転のマップ構築にも応用されている。",
    links: { arxiv: "https://arxiv.org/abs/2003.08934", github: "https://github.com/bmild/nerf" }
  },
  {
    id: "instant-ngp",
    title: "Instant Neural Graphics Primitives with a Multiresolution Hash Encoding",
    titleJa: "Instant-NGP：マルチ解像度ハッシュ符号化による超高速NeRF",
    authors: "Thomas Müller, Alex Evans, Christoph Schied, Alexander Keller",
    year: 2022,
    venue: "SIGGRAPH 2022",
    tags: ["3D", "NeRF", "高速化"],
    summary: "本論文では、多種の神経グラフィクスタスク（NeRF・符号付き距離関数・ニューラルイラジアンスキャッシュ等）において学習・推論速度を大幅に向上させるための小型だが強力なタスクに依存しない補助データ構造、マルチ解像度ハッシュエンコーディングを提案する。このエンコーディングは、CUDA による完全並列実装が可能であり、入力座標を複数の解像度レベルのグリッドに配置し、各グリッド頂点の特徴ベクトルをコンパクトなハッシュテーブルに格納する。これにより、シーン 1 件あたりの学習コストを従来NeRF（数時間）から数秒〜数分に削減しながら、同等以上の合成品質を達成する。後続の小型 MLP は補助データ構造が提供する豊富な特徴量を活用するためにコンパクトに保てる。NeRF において、Instant-NGP は5秒以内の高速プロトタイプ学習を可能にし、Mip-NeRF 360 と同水準以上の品質を Tanks and Temples・Deep Blending 等のシーンで示した。",
    background: "NeRFは新規視点合成の品質で革新をもたらしたが、単一シーンの学習に数時間・推論にも数秒かかる計算コストがリアルタイム応用や実用展開の障壁となっていた。",
    method: "シーン空間を16段階のマルチ解像度グリッドで管理。各グリッド点の特徴ベクトルをCUDA最適化されたハッシュテーブルで保持し、入力座標からバイリニア補間で特徴を取得。後段の小型MLPで色・密度を予測する。",
    results: "NeRFと同等以上の品質を保ちながら学習時間を10〜1000倍短縮。5秒でFinetuneされたモデルが、従来NeRFの数時間分の品質に近い結果を出す。",
    discussion: "Instant-NGPはその後NeRF系研究の標準的な高速化ベースラインとなり、3D Gaussian Splattingへの移行期においても重要な参照手法であり続けている。NVIDIAが公式実装を提供しており産業応用事例も多い。",
    links: { arxiv: "https://arxiv.org/abs/2201.05989", github: "https://github.com/NVlabs/instant-ngp" }
  },
  // ===== 認識 / アーキテクチャ =====
  {
    id: "swin",
    title: "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows",
    titleJa: "Swin Transformer：シフトウィンドウを用いた階層型ビジョントランスフォーマー",
    authors: "Ze Liu, Yutong Lin, Yue Cao, Han Hu, Yixuan Wei, Zheng Zhang, Stephen Lin, Baining Guo",
    year: 2021,
    venue: "ICCV 2021",
    tags: ["認識", "Transformer", "Vision"],
    summary: "本論文では、Swin Transformer（Shifted Window Transformer）と呼ぶ新しいビジョン Transformer を提案する。Swin Transformer は、小さなパッチから始まり、より深い Transformer 層で隣接パッチをマージしていく階層的な特徴マップを構築するよう設計されている。Attention の計算は各画像をオーバーラップしない局所ウィンドウ内のみで行い、その後ウィンドウを規則的にシフトすることでウィンドウ間の接続を実現する。この設計により計算複雑度は画像サイズに対して線形となり、幅広い解像度の画像に適応できる。ImageNet 1K 画像分類において Top-1 87.3%（ViT-B/16 の 81.8% を大幅に上回る）を達成するとともに、COCO 物体検出（box AP 58.7）・ADE20K セマンティックセグメンテーション（mIoU 53.5）で SoTA を更新した。畳み込みニューラルネットワークに倣った階層構造と Attention 計算の局所化が、ビジョン分野の汎用バックボーンとして機能する上での鍵となっている。",
    background: "ViTは大規模データで強力な性能を示したが、全パッチ間のAttentionは計算量が画像サイズの二乗に比例するため高解像度用途に向かず、また固定パッチサイズのため物体検出等への流用が難しかった。",
    method: "固定サイズのウィンドウ内でのみLocal Self-Attentionを実施し、交互にウィンドウをシフトさせることで非局所的な情報伝播を実現。4段のステージ構成で空間解像度を1/4→1/8→1/16→1/32と縮小する。",
    results: "ImageNet Top-1 87.3%（ViT-B/16の81.8%を大幅に上回る）。COCO物体検出（box AP 58.7）・ADE20Kセグメンテーション（mIoU 53.5）でSoTAを更新。",
    discussion: "Swin TransformerはCNNとViTの設計思想を融合した汎用バックボーンとして多用途に利用されており、セグメンテーション・動画理解・医用画像など多くの後続研究の基盤となっている。",
    links: { arxiv: "https://arxiv.org/abs/2103.14030", github: "https://github.com/microsoft/Swin-Transformer" }
  },
  {
    id: "mae",
    title: "Masked Autoencoders Are Scalable Vision Learners",
    titleJa: "MAE：マスク付き自己符号化器は大規模ビジョン学習に有効である",
    authors: "Kaiming He, Xinlei Chen, Saining Xie, Yanghao Li, Piotr Dollár, Ross Girshick",
    year: 2022,
    venue: "CVPR 2022",
    tags: ["自己教師あり学習", "Vision Transformer", "表現学習"],
    summary: "本論文では、マスク付き自己符号化器（Masked Autoencoders, MAE）がスケーラブルなビジョン学習手法として機能することを示す。アプローチは単純で、入力画像のランダムなパッチをマスクし、欠損したピクセルを再構成することを学習する。MAE の有効性を支える 2 つの核心的な設計がある。第一に、非常に高いマスク率（75〜80%）が有意義な自己教師あり学習タスクを生み出す点。第二に、エンコーダはマスクされていないパッチのみを処理し、[MASK]トークンを含む完全シーケンスは軽量デコーダにのみ渡す非対称エンコーダ・デコーダ構造が学習効率を大幅に向上させる点。この設計により、訓練速度は従来の ViT と比較して 3 倍以上高速化される。ImageNet-1K のみでの事前学習後にファインチューニングを行うと、ViT-Large で Top-1 87.8% を達成した。転移学習においても物体検出・セグメンテーション・動画認識で教師あり事前学習を一貫して上回ることを確認した。",
    background: "自己教師あり学習はNLPで大きな成功を収めたが、ビジョンへの単純な適用（BEiTなど）は計算コストが高く、画像の空間的冗長性への対処が課題だった。",
    method: "ランダムサンプリングで75〜80%のパッチをマスク。可視パッチのみViT-Encoderへ入力し、[MASK]トークンを含む完全シーケンスを軽量Decoderに渡して元ピクセルを予測する。",
    results: "ImageNet-1K線形評価76.0%、ファインチューニング87.8%（ViT-L）。物体検出・セグメンテーション・動画認識での転移学習でも教師あり事前学習を上回った。",
    discussion: "シンプルかつ効果的なMAEは大規模ビジョン基盤モデルの事前学習戦略として広く採用されている。動画MAE・Audio MAEなどへの拡張も活発で、マルチモーダル表現学習への波及効果も大きい。",
    links: { arxiv: "https://arxiv.org/abs/2111.06377", github: "https://github.com/facebookresearch/mae" }
  },
  // ===== マルチモーダル =====
  {
    id: "clip",
    title: "Learning Transferable Visual Models From Natural Language Supervision",
    titleJa: "CLIP：自然言語監督による転移可能な視覚モデルの学習",
    authors: "Alec Radford, Jong Wook Kim, Chris Hallacy, Aditya Ramesh, Gabriel Goh, Sandhini Agarwal, Girish Sastry, Amanda Askell, Pamela Mishkin, Jack Clark, Gretchen Krueger, Ilya Sutskever",
    year: 2021,
    venue: "ICML 2021",
    tags: ["マルチモーダル", "自己教師あり学習", "ゼロショット"],
    summary: "本論文では、自然言語監督から転移可能な視覚モデルを学習する効果的かつスケーラブルな手法を提案する。CLIP（Contrastive Language-Image Pre-Training）は、インターネットから収集した 4 億の画像・テキストペアを用いてコントラスト学習により画像エンコーダとテキストエンコーダを同時に学習する。学習後、テキストエンコーダは任意のビジュアル分類器を生成するために使用でき、下流のデータセットに特化したトレーニングを一切行わなくても ImageNet において Top-1 76.2%（ResNet-50 の教師あり 76.1% と同等）を達成する。さらに 30 以上のビジョンベンチマーク（OCR・動画認識・地理推定・細粒度分類・行動認識など）において優れた汎化性能を示し、多くのデータセット固有教師あり手法と競争力ある結果を残した。また自然言語監督により学習した視覚モデルは、従来の標準的なベンチマーク集合からは発見しにくいロバスト性を持つことも示している。",
    background: "従来の視覚モデルは固定されたラベル集合で学習するため、ゼロショット転移が困難だった。自然言語は任意の概念を表現できるため、より柔軟な監督信号として機能しうると考えられていた。",
    method: "ResNetまたはViT系の画像エンコーダとTransformerテキストエンコーダを、4億ペアのWebスクレイピングデータに対する対照学習（InfoNCE損失）で同時に学習する。",
    results: "ImageNetゼロショット Top-1 76.2%（ResNet-50の教師あり76.1%と同等）。27タスク中16タスクで教師あり線形探索を上回る転移性能を達成。",
    discussion: "CLIPは生成モデル（DALL-E・Stable Diffusion）の条件付けや物体検出・セグメンテーションの汎化など、その後のビジョン研究の礎となった。オープンソース実装（OpenCLIP）も広く普及している。",
    links: { arxiv: "https://arxiv.org/abs/2103.00020", github: "https://github.com/openai/CLIP" }
  },
  {
    id: "llava",
    title: "Visual Instruction Tuning",
    titleJa: "LLaVA：視覚的指示チューニングによる大規模マルチモーダルモデル",
    authors: "Haotian Liu, Chunyuan Li, Qingyang Wu, Yong Jae Lee",
    year: 2023,
    venue: "NeurIPS 2023",
    tags: ["マルチモーダル", "大規模言語モデル", "視覚言語"],
    summary: "本論文では、ビジュアルインストラクションチューニングと呼ぶ初の取り組みにより、大規模マルチモーダルモデル（Large Multimodal Model, LMM）の構築を行う。GPT-4 を活用して画像・テキストの対話形式訓練データを言語だけの入力から自動生成するデータ生成パイプラインを構築し、158k 件のインストラクションフォロイングデータを作成した。モデルアーキテクチャは、画像エンコーダ（CLIP ViT-L/14）の出力を線形射影によって LLM（LLaMA/Vicuna）のトークン埋め込み空間にマッピングし、テキストトークンと連結した後に言語モデルへ入力するシンプルな構造を採用する。二段階の訓練（特徴アライメント → エンドツーエンドのインストラクションチューニング）で学習を行う。LLaVA-Bench による評価では GPT-4 比で 85.1% の相対スコアを達成し、ScienceQA では 92.53% と GPT-4 単体（83.99%）を上回る SoTA を達成した。本研究は大規模マルチモーダルモデルのオープンソース研究の先駆けとなった。",
    background: "GPT-4Vのようなマルチモーダルモデルは強力だが非公開。オープンソースコミュニティが同等の性能のモデルを構築・研究できる環境が求められていた。また視覚的指示チューニング用の大規模データセットが存在しなかった。",
    method: "CLIPで画像特徴を抽出→線形射影でLLM埋め込み空間へマッピング→言語モデルと連結。まず画像キャプションデータで特徴アライメント、次に生成した対話データでInstruction Tuningを実施。",
    results: "LLaVA-Benchmarkで既存オープンソースモデルを大幅に上回り、GPT-4（テキストのみ）比で視覚的QAで85.1%の性能。ScienceQAでは94.88%（GPT-4は83.99%）を達成。",
    discussion: "LLaVAの提案したアーキテクチャ・データ生成パイプラインは後継のLLaVA-1.5・LLaVA-NeXTなどに発展し、マルチモーダルLLMのオープンソース研究を大きく活性化させた。",
    links: { arxiv: "https://arxiv.org/abs/2304.08485", github: "https://github.com/haotian-liu/LLaVA" }
  },
  // ===== セキュリティ / 頑健性 =====
  {
    id: "obfuscated-gradients",
    title: "Obfuscated Gradients Give a False Sense of Security: Circumventing Defenses to Adversarial Examples",
    titleJa: "難読化勾配は誤った安全感を与える：敵対的サンプル防御の回避",
    authors: "Anish Athalye, Nicholas Carlini, David Wagner",
    year: 2018,
    venue: "ICML 2018",
    tags: ["敵対的頑健性", "セキュリティ", "機械学習"],
    summary: "本論文では、勾配ベースの敵対的サンプル攻撃に対する多くの防御手法が、勾配の難読化（Obfuscated Gradients）という共通の弱点に依存していることを明らかにする。難読化された勾配は攻撃者の最適化を誤動作させるが、防御手法が真に頑健であることを意味しない。我々は難読化勾配の 3 つのパターン（Shattered Gradients・Stochastic Gradients・Vanishing/Exploding Gradients）を同定し、それぞれを回避するためのテクニック—前向き差分近似を用いる BPDA、確率的変換の期待値を取る EOT、入力を再パラメータ化して微分可能にする手法—を提案する。ICLR 2018 に採択された 7 本の防御論文に対してこれらの手法を適用した結果、そのうち 6 本を完全に無効化することに成功した。真の頑健性を持つ唯一の防御手法は Adversarial Training であることを確認した。本研究は、防御手法の評価においては提案手法に特化した適応的攻撃（Adaptive Attack）を用いた評価が不可欠であることを強調する。",
    background: "拡張版防御論文が多数発表されていたが、PGD攻撃のような強力な白箱攻撃に対して本当に頑健かどうか評価が不十分なまま採択される問題が指摘されていた。",
    method: "3種の難読化パターンに対してそれぞれ専用の攻撃手法を設計。BPDA（後方パスを微分可能な近似で置換）、EOT（確率的変換の期待値を最適化）を提案。",
    results: "調査した7本の防御手法のうち6本を100%近い成功率で突破。残る1本（Adversarial Training）のみが本質的な頑健性を持つことを確認。",
    discussion: "この研究はMLセキュリティコミュニティに大きな衝撃を与え、防御手法の評価基準を根本的に見直させた。現在も防御論文では「Adaptive Attack評価」が必須とされるようになっており、本論文はその契機となった。",
    links: { arxiv: "https://arxiv.org/abs/1802.00420", github: "https://github.com/anishathalye/obfuscated-gradients" }
  },
  // ===== 以下は既存のエントリ =====
  {
    id: "detr",
    title: "End-to-End Object Detection with Transformers",
    titleJa: "DETR：Transformerによるエンドツーエンド物体検出",
    authors: "Nicolas Carion, Francisco Massa, Gabriel Synnaeve, Nicolas Usunier, Alexander Kirillov, Sergey Zagoruyko",
    year: 2020,
    venue: "ECCV 2020",
    tags: ["Object Detection", "Transformer", "Vision"],
    summary: "本論文では、物体検出をセット予測問題として捉え直し、検出パイプラインを効果的に簡略化する新しいモデル DETR（DEtection TRansformer）を提案する。DETR はアンカー生成・非最大値抑制（NMS）などの手作業によるコンポーネントをすべて除去し、Transformer のエンコーダ・デコーダアーキテクチャと二部マッチングに基づく集合損失関数を用いてエンドツーエンドで物体検出を行う。デコーダは固定数の学習済みオブジェクトクエリを用いて予測ボックスを並列出力し、ハンガリアンアルゴリズムが予測と正解ボックスを 1 対 1 に対応させる。COCO 検出ベンチマークにおいて、最適化された Faster R-CNN ベースラインと同等の精度（AP 42.0）を達成し、特に大きな物体の検出において顕著な優位性を示した。本手法のシンプルな構造はパノプティックセグメンテーションへの拡張も容易であることを示した。",
    background: "物体検出は長らく、アンカーボックスの設計・非最大値抑制（NMS）など多くの手作業によるコンポーネントに依存していた。これらはタスク固有の知識を必要とし、エンドツーエンドの学習を妨げる要因となっていた。",
    method: "Transformerのエンコーダが画像特徴マップを文脈化し、デコーダが学習済みオブジェクトクエリを用いて並列に予測を行う。ハンガリアンアルゴリズムによる二部マッチング損失で、予測と正解ボックスを1対1対応させる。",
    results: "COCO valセットにおいてFaster R-CNNと同等の精度（AP 42.0）を達成。特に大きな物体の検出において優れた性能を示した。モデルはアンカーやNMSなどの設計が不要でシンプルな構造を維持している。",
    discussion: "Transformerを物体検出に初めて本格的に適用した先駆的研究であり、後続のViT系モデルや多くの検出手法に影響を与えた。一方で、学習に時間がかかる点や小物体への対応が課題として残る。",
    links: { arxiv: "https://arxiv.org/abs/2005.12872", github: "https://github.com/facebookresearch/detr" }
  },
  {
    id: "diffusion-adversarial",
    title: "Adversarial Purification with Score-based Generative Models",
    titleJa: "スコアベース生成モデルによる敵対的摂動の浄化",
    authors: "Jongmin Yoon, Sung Ju Hwang, Juho Lee",
    year: 2021,
    venue: "ICML 2021",
    tags: ["Adversarial Robustness", "Diffusion Model", "Defense"],
    summary: "本論文では、スコアベースの生成モデル（拡散モデル）を用いて敵対的摂動を前処理として除去する新しい防御手法を提案する。入力画像に小量のガウシアンノイズを加えてから、スコア関数によるランゲビン動力学のサンプリング（逆拡散）を適用し、摂動を自然な画像多様体上の点へと引き戻す。この浄化後の画像を標準の分類器に入力することで、敵対的摂動に対して頑健な予測が得られる。この手法の重要な利点は、攻撃手法を仮定しないため、ホワイトボックス・ブラックボックス・転移攻撃など多様な種類の攻撃に対して汎化的な防御効果を持つ点である。CIFAR-10・ImageNet を用いた評価において、AutoAttack・PGD などの強力な攻撃に対して Adversarial Training ベースラインと競争力ある精度を達成した。",
    background: "深層学習モデルは微小な敵対的摂動に対して脆弱であることが知られている。従来のAdversarial Training等の防御手法はホワイトボックス攻撃に対しては有効だが、未知の攻撃への汎化性に課題があった。",
    method: "スコアベースモデルを使い、入力画像に対してランゲビン動力学によるサンプリングを行う。これにより高次元データ空間において、敵対的摂動を自然な画像多様体上の点へと引き戻す効果が得られる。",
    results: "CIFAR-10に対するAutoAttackにおいて、Adversarial Trainingと比較して競争力のある精度を達成。特に転移攻撃や各種ブラックボックス攻撃に対して高い頑健性を示した。",
    discussion: "生成モデルを防御に活用するアプローチの有効性を示した。ただし、推論時のサンプリングコストが高く、リアルタイム用途への適用には課題がある。",
    links: { arxiv: "https://arxiv.org/abs/2106.06041" }
  },
  {
    id: "yolov8",
    title: "YOLOv8: A New State-of-the-Art Vision Model",
    titleJa: "YOLOv8：新世代のリアルタイム物体検出モデル",
    authors: "Glenn Jocher, Ayush Chaurasia, Jing Qiu",
    year: 2023,
    venue: "Ultralytics (Technical Report)",
    tags: ["Object Detection", "Real-time", "Vision"],
    summary: "Ultralytics が開発した YOLOv8 は、アンカーフリーのアーキテクチャを採用した物体検出・インスタンスセグメンテーション・ポーズ推定・分類を統合する最新世代の汎用ビジョンモデルである。バックボーンには C2f（Cross Stage Partial with 2 feature fusion）モジュールを採用し、従来の C3 モジュールと比較してより多くのグラジェント情報を伝播できる設計となっている。ヘッドはデカップルド構造を採用し、分類タスクと回帰タスクを独立した分岐で処理することで精度向上を図る。COCO val2017 ベンチマークにおいて、YOLOv8n は AP 37.3・速度 0.99 ms（A100 GPU）を達成し、精度・速度ともに YOLOv5 を上回る。小型（n/s）から大型（m/l/x）まで 5 段階のモデルスケールを提供しており、リソース制約に応じた選択が可能。シンプルな Python API と広範なエコシステムにより、研究・産業応用での利用が急速に広がっている。",
    background: "YOLOシリーズは速度と精度のバランスに優れるリアルタイム検出モデルとして広く利用されてきた。YOLOv5以降のアーキテクチャ進化を踏まえ、さらなる精度向上と使いやすさの改善が求められていた。",
    method: "C2fバックボーンによる特徴抽出、アンカーフリーのデカップルドヘッド採用により柔軟な検出が可能。DeformableConvや分類・回帰損失の分離など複数の改良を統合している。",
    results: "COCO val2017においてYOLOv5比で精度・速度ともに向上。特にYOLOv8nはGPU/CPUの両環境で高いスループットを維持しつつAP 37.3を達成した。",
    discussion: "Ultralytics社によって積極的にメンテナンスされており、産業応用から研究まで幅広く使われている。マルチタスク対応の統一フレームワークとして実用性が高い。",
    links: { github: "https://github.com/ultralytics/ultralytics" }
  },
  {
    id: "sam",
    title: "Segment Anything",
    titleJa: "SAM：あらゆるものをセグメンテーションする汎用モデル",
    authors: "Alexander Kirillov, Eric Mintun, Nikhila Ravi, Hanzi Mao, Chloe Rolland, Laura Gustafson, Tete Xiao, Spencer Whitehead, Alexander C. Berg, Wan-Yen Lo, Piotr Dollár, Ross Girshick",
    year: 2023,
    venue: "ICCV 2023",
    tags: ["Segmentation", "Foundation Model", "Vision"],
    summary: "本論文では、大規模な基盤モデルを構築するためのプロジェクトを通じてセグメンテーションタスクの課題を解決することを目指す Segment Anything（SA）プロジェクトを紹介する。本研究は、プロンプタブルなセグメンテーションタスクの定義・広範なデータ収集に用いるモデル（SAM）・1B 以上のマスクを含む世界最大のセグメンテーションデータセット SA-1B の 3 つの構成要素からなる。SAM は点・ボックス・テキスト・マスクなど多様なプロンプトに応じて任意のオブジェクトのマスクをリアルタイムで出力するプロンプタブルなアーキテクチャを採用する。モデルは画像エンコーダ（ViT-H）・プロンプトエンコーダ・軽量マスクデコーダの 3 モジュールで構成され、インタラクティブに洗練させることが可能。23 種類のセグメンテーションタスクにわたるゼロショット転移評価において、専門データで学習した教師あり手法と競争力ある性能を示し、汎用セグメンテーション基盤モデルの実現可能性を実証した。",
    background: "画像セグメンテーションはラベル付きデータの収集コストが高く、特定ドメインへの特化が多かった。NLPにおけるGPTのような汎用基盤モデルをビジョン分野に実現することが目標とされていた。",
    method: "画像エンコーダ（ViT-H）・プロンプトエンコーダ・マスクデコーダの3モジュール構成。1B以上のマスクを含むSA-1Bデータセットで学習し、インタラクティブプロンプトに対してリアルタイムにマスクを生成する。",
    results: "23の異なるセグメンテーションタスクでゼロショット転移の有効性を実証。専門データで学習した教師ありモデルと競争力ある性能を示した。",
    discussion: "「基盤モデル」のコンセプトをビジョン分野に広め、ダウンストリームタスクへの活用が急拡大している。ドローン画像・医用画像等への応用も活発に研究されている。",
    links: { arxiv: "https://arxiv.org/abs/2304.02643", github: "https://github.com/facebookresearch/segment-anything" }
  },
  {
    id: "vit",
    title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
    titleJa: "ViT：画像は16×16ワードの価値がある — 大規模画像認識のためのTransformer",
    authors: "Alexey Dosovitskiy, Lucas Beyer, Alexander Kolesnikov, Dirk Weissenborn, Xiaohua Zhai, Thomas Unterthiner, Mostafa Dehghani, Matthias Minderer, Georg Heigold, Sylvain Gelly, Jakob Uszkoreit, Neil Houlsby",
    year: 2021,
    venue: "ICLR 2021",
    tags: ["Vision Transformer", "Classification", "Attention"],
    summary: "本論文では、純粋な Transformer をシーケンスとして扱った画像パッチに適用することで、画像認識においても Transformer が十分に機能することを示す。画像を固定サイズのパッチに分割し、各パッチを線形に埋め込んで位置エンコーディングを付与した後、標準的な Transformer エンコーダに入力する。大規模データセット（JFT-300M）で事前学習を行うことで CNN の帰納バイアスを補い、ImageNet において当時の SoTA を更新する Top-1 88.55%（ViT-L/16）を達成した。中規模データセット（ImageNet-21k）での事前学習では正則化の重要性が示され、データスケールへの依存性が CNN とは異なる特性を持つことも明らかにした。本研究はビジョン分野への Transformer の応用が実用的であることを初めて大規模に実証し、その後の DeiT・Swin Transformer・BEiT など多数の後継研究の礎を築いた。",
    background: "NLP分野ではTransformerが支配的となっていたが、ビジョン分野ではCNNが主流であった。畳み込みの帰納バイアスなしに画像をモデル化できるか、という問いへの挑戦として本研究が行われた。",
    method: "画像を16×16ピクセルのパッチに分割し、各パッチを線形埋め込みでトークン化。位置埋め込みを加えた後、標準的なTransformerエンコーダに入力する。クラストークンによって最終的なクラス予測を行う。",
    results: "JFT-300M等の大規模データで事前学習したViT-Lは、ImageNetでtop-1精度88.55%を達成し、当時のSoTAを更新。中規模データでは正則化の重要性が示された。",
    discussion: "ViTはその後のDeiT・Swin Transformer・BEiT等、多数の後継研究の基盤となった。ビジョンとNLPの統一的なアーキテクチャへの道を開いた重要論文。",
    links: { arxiv: "https://arxiv.org/abs/2010.11929", github: "https://github.com/google-research/vision_transformer" }
  },
  // ===== CV系トップカンファレンス 最新論文 =====
  {
    id: "controlnet",
    title: "Adding Conditional Control to Text-to-Image Diffusion Models",
    titleJa: "ControlNet：テキストから画像生成拡散モデルへの条件付き制御の追加",
    authors: "Lvmin Zhang, Anyi Rao, Maneesh Agrawala",
    year: 2023,
    venue: "ICCV 2023",
    tags: ["生成AI", "拡散モデル", "条件付き生成", "画像生成"],
    summary: "本論文では、大規模な事前学習済みテキストから画像への拡散モデルに対して、ポーズ・深度・エッジ・セグメンテーションマスクなどの空間条件付き制御を追加するニューラルネットワーク構造 ControlNet を提案する。ControlNet は元の拡散モデルのエンコーダブロックを「ロック」したコピーと「学習可能」なコピーに分割し、後者にのみ条件付き情報を注入することで元モデルの豊富な知識を保持しながら新たな制御を学習する。学習可能なコピーと元のコピーをゼロ畳み込み（重みゼロで初期化された 1×1 畳み込み）で接続することで、学習開始時に有害なノイズが元モデルに影響しないよう設計されている。HED エッジ・人体ポーズ・深度マップ・セグメンテーションマップ・落書き等、多様な入力形式での条件付き画像生成を実証した。ユーザースタディおよび定量評価において、特定の空間制約を持つ高品質な画像生成において既存手法（Textual Inversion・DreamBooth 等）を大幅に上回ることを示した。",
    background: "既存の拡散モデルはテキストプロンプトによる制御が主流だったが、ポーズ・構図・形状などを精密に指定した画像生成はテキストだけでは困難だった。特定の空間構造を保ちながら高品質な画像を生成する手法が求められていた。",
    method: "事前学習済みUNetのエンコーダを複製し、学習可能なコピーにのみ条件入力を注入。ゼロ畳み込みで元モデルと結合することで、初期学習時のノイズを防ぎながら効率的に条件制御を学習する。",
    results: "ポーズ・深度・エッジなど多様な条件付き生成タスクで高品質な結果を達成。ユーザースタディで既存の制御手法を大幅に上回り、小規模データセット（数十〜数百枚）でも良好な学習が可能なことを示した。",
    discussion: "ControlNetはStable Diffusionエコシステムに深く統合され、イラスト・デザイン・映像制作など実用分野への影響が極めて大きい。その後アニメーション・動画生成への拡張（AnimateDiff + ControlNet等）も活発に研究されている。",
    links: { arxiv: "https://arxiv.org/abs/2302.05543", github: "https://github.com/lllyasviel/ControlNet" }
  },
  {
    id: "dinov2",
    title: "DINOv2: Learning Robust Visual Features without Supervision",
    titleJa: "DINOv2：教師なしで頑健な視覚特徴を学習する",
    authors: "Maxime Oquab, Timothée Darcet, Théo Moutakanni, Huy Vo, Marc Szafraniec, Vasil Khalidov, Pierre Fernandez, Daniel Haziza, Francisco Massa, Alaaeldin El-Nouby, Mahmoud Assran, Nicolas Ballas, Wojciech Galuba, Russell Howes, Po-Yao Huang, Shang-Wen Li, Ishan Misra, Michael Rabbat, Vasu Sharma, Gabriel Synnaeve, Hu Xu, Hervé Jégou, Julien Mairal, Patrick Labatut, Armand Joulin, Piotr Bojanowski",
    year: 2024,
    venue: "TMLR 2024",
    tags: ["自己教師あり学習", "Foundation Model", "Vision Transformer", "表現学習"],
    summary: "本論文では、自己教師あり学習のみを用いて、広範な視覚タスクに直接利用可能な汎用的な凍結特徴量を生成する基盤モデル DINOv2 を提案する。大規模かつ厳選された画像データセット LVD-142M（1 億 4200 万枚）を構築し、DiscriminativeSelf-supervised Learning（DINO・iBOT）とマスク画像モデリングを組み合わせたパイプラインで学習を行う。特にデータキュレーションのパイプラインを精緻化し、重複排除・クラスタリング・品質フィルタリングを通じて多様かつ高品質な学習データを確保した。学習された特徴は追加のファインチューニングなしに、深度推定・セマンティックセグメンテーション・画像分類・インスタンス検索など多様なタスクで最先端の性能を示す。ViT-g（1B パラメータ）を含む複数スケールのモデルを提供し、ダウンストリームタスクへの転移において教師あり事前学習と同等以上の性能を発揮することを実証した。",
    background: "既存の自己教師あり学習（MAE・MoCo等）は特定タスクへのファインチューニングが前提であり、凍結特徴量のみで広範なビジョンタスクに対応できる汎用モデルが存在しなかった。NLPにおけるGPT系モデルのような「汎用ビジョン基盤」の実現が求められていた。",
    method: "LVD-142Mデータセットで学習。DINO（自己蒸留）とiBOT（マスク画像予測）を組み合わせたパイプライン。KoLeo正則化・LayerScale・Flash Attentionなど多数の工夫で大規模ViT（ViT-g/14）を安定学習させる。",
    results: "ImageNet線形評価86.5%（ViT-g）。セマンティックセグメンテーション・深度推定・画像検索等、多様なタスクで凍結特徴のみでSoTAを更新または同等性能を達成。",
    discussion: "DINOv2は視覚基盤モデル研究の標準的な参照点となっており、Depth Anything・Grounding DINOなど多数の後続研究がそのバックボーンとして採用している。ビジョンとNLPの汎用モデル統合への重要な一歩。",
    links: { arxiv: "https://arxiv.org/abs/2304.07193", github: "https://github.com/facebookresearch/dinov2" }
  },
  {
    id: "sdxl",
    title: "SDXL: Improving Latent Diffusion Models for High-Resolution Image Synthesis",
    titleJa: "SDXL：高解像度画像合成のための潜在拡散モデルの改良",
    authors: "Dustin Podell, Zion English, Kyle Lacey, Andreas Blattmann, Tim Dockhorn, Jonas Müller, Joe Penna, Robin Rombach",
    year: 2024,
    venue: "ICLR 2024",
    tags: ["生成AI", "拡散モデル", "高解像度", "画像生成"],
    summary: "本論文では、Stable Diffusion の後継として大幅に強化された高解像度テキストから画像生成モデル SDXL を提案する。3 倍のパラメータ数を持つ U-Net バックボーン（33 億パラメータ）と、短い・長いテキスト記述の両方を扱える 2 つのテキストエンコーダ（OpenCLIP ViT-bigG・CLIP ViT-L）を組み合わせる。また基本モデルの出力を高解像度で洗練するリファイナーモデルとの 2 段構成を採用し、より細かい詳細と忠実度の高い画像生成を実現する。新機能として、画像のオリジナル解像度・クロップ情報を条件付けに加えることで不自然な切り取りや品質劣化を抑制するサイズ・クロップ条件付けを導入する。人間の好みを評価した大規模なユーザースタディにおいて、同サイズ・同スケールの比較可能な拡散ベースモデルすべてを上回り、Stable Diffusion 1.5・2.1 と比較して著しく高い品質の画像を生成することを示した。",
    background: "Stable Diffusion 1.x/2.xは低解像度・単純な構図では良好だが、複雑なプロンプトや高解像度で品質が安定しない問題があった。また人の手指・テキスト描写など細部の品質向上が求められていた。",
    method: "3倍のU-Netパラメータと2つのテキストエンコーダによる強力な条件付け。サイズ・クロップ条件付けで学習データのバイアスを軽減。Refinerモデルとの2段パイプラインで高品質な最終出力を得る。",
    results: "人間評価において同等クラスの拡散モデルすべてを上回る生成品質を達成。特に人物・細部描写・テキスト描画において大幅な改善を示した。",
    discussion: "SDXLはその後オープンソースコミュニティで広く採用され、LoRA・ControlNet等の拡張と組み合わせた応用研究が急増した。Stable Diffusion 3・Fluxへと続くラインの重要なマイルストーンとなっている。",
    links: { arxiv: "https://arxiv.org/abs/2307.01952", github: "https://github.com/Stability-AI/generative-models" }
  },
  {
    id: "instructpix2pix",
    title: "InstructPix2Pix: Learning to Follow Image Editing Instructions",
    titleJa: "InstructPix2Pix：画像編集指示に従う学習",
    authors: "Tim Brooks, Aleksander Holynski, Alexei A. Efros",
    year: 2023,
    venue: "CVPR 2023",
    tags: ["生成AI", "画像編集", "拡散モデル", "指示チューニング"],
    summary: "本論文では、自然言語の指示（「猫を犬にして」「夕焼けにして」等）に従って入力画像を編集する汎用的な手法 InstructPix2Pix を提案する。GPT-3 が生成した画像編集指示と Prompt-to-Prompt で作成した前後の画像ペアを組み合わせて大規模な合成学習データセット（45 万ペア以上）を構築する。このデータで条件付き拡散モデルをファインチューニングすることで、テスト時に推論・最適化なしで任意の実写画像・指示の組み合わせに汎化できるモデルが得られる。2 つのガイダンス係数（テキストガイダンス・画像保持ガイダンス）を導入することで、編集内容の強度と入力画像への忠実度のトレードオフを制御できる。人間評価において、DALL-E・DreamBooth などの比較手法と比較して、指示への整合性と画像品質の両面で高評価を得た。",
    background: "既存の画像生成・編集手法は、テキストプロンプトで新規画像を生成することには優れていたが、入力画像の構造・スタイルを保ちながら指定した変更のみを適用する「指示に従った画像編集」は困難だった。",
    method: "GPT-3で（元プロンプト, 編集指示, 編集後プロンプト）の三つ組みを大量生成し、Prompt-to-Promptで対応する画像ペアを合成。このデータでLatent Diffusion Modelをファインチューニングする。",
    results: "人間評価において指示整合性と視覚品質の両面で比較手法を上回る。テスト時に追加最適化なしで多様な実写・アート画像に汎化することを実証。",
    discussion: "合成データによる学習パイプラインの有効性を示した点が重要であり、その後の指示ファインチューニング・画像編集研究の参照手法として広く引用されている。",
    links: { arxiv: "https://arxiv.org/abs/2211.09800", github: "https://github.com/timothybrooks/instruct-pix2pix" }
  },
  {
    id: "grounding-dino",
    title: "Grounding DINO: Marrying DINO with Grounded Pre-Training for Open-Set Object Detection",
    titleJa: "Grounding DINO：オープンセット物体検出のためのDINOと接地事前学習の融合",
    authors: "Shilong Liu, Zhaoyang Zeng, Tianhe Ren, Feng Li, Hao Zhang, Jie Yang, Chunyuan Li, Jianwei Yang, Hang Su, Jun Zhu, Lei Zhang",
    year: 2024,
    venue: "ECCV 2024",
    tags: ["Object Detection", "Vision-Language", "オープンセット", "Foundation Model"],
    summary: "本論文では、クローズドセット物体検出器 DINO と接地事前学習を組み合わせることで、任意のテキストクエリに対して物体を検出できるオープンセット物体検出器 Grounding DINO を提案する。Transformer ベースの検出器である DINO（DETR の後継）のアーキテクチャに言語バックボーン（BERT）を統合し、フィーチャーエンハンサー・言語誘導クエリ選択・クロスモダリティデコーダという 3 つの融合モジュールを設計することで、テキストと視覚特徴の深い統合を実現する。COCO・LVIS・ODinW・RefCOCO など多数のベンチマークにおいて、ゼロショット物体検出の精度で既存の開放語彙物体検出手法（GLIP・OWL-ViT 等）を大幅に上回り、COCO ゼロショット検出 AP 52.5 を達成した。SAM と組み合わせた Grounded SAM では任意テキストによるセグメンテーションも実現している。",
    background: "従来の物体検出モデルはトレーニング時のカテゴリ集合しか検出できないクローズドセットだった。自動運転・ロボット・医療など実環境では未知クラスも含めて検出する汎用性が求められていた。",
    method: "DINOのTransformer検出器にBERTテキストエンコーダを統合。フィーチャーエンハンサーでマルチスケール視覚特徴とテキスト特徴を融合し、言語誘導クエリ選択で関連する検出クエリを選択。クロスモダリティデコーダで最終予測を行う。",
    results: "COCO ゼロショット検出AP 52.5を達成。ODinW-35の35カテゴリゼロショット設定でも既存手法を大幅上回る。SAMとの組み合わせで任意テキストによるオープンセットセグメンテーションを実現。",
    discussion: "オープンセット物体検出の実用化において重要な前進であり、ロボット・医療診断・産業検査への応用が活発に研究されている。Grounded SAMとして公開されオープンソースコミュニティで広く利用されている。",
    links: { arxiv: "https://arxiv.org/abs/2303.05499", github: "https://github.com/IDEA-Research/GroundingDINO" }
  },
  {
    id: "videomae-v2",
    title: "VideoMAE V2: Scaling Video Masked Autoencoders with Dual Masking",
    titleJa: "VideoMAE V2：デュアルマスキングによる動画マスク自己符号化器のスケーリング",
    authors: "Limin Wang, Bingkun Huang, Zhiyu Zhao, Zhan Tong, Yinan He, Yi Wang, Yali Wang, Yu Qiao",
    year: 2023,
    venue: "CVPR 2023",
    tags: ["動画理解", "自己教師あり学習", "Vision Transformer", "表現学習"],
    summary: "本論文では、VideoMAE の拡張として、デュアルマスキング戦略によって動画の自己教師あり学習を大規模スケールで効率的に実現する VideoMAE V2 を提案する。デュアルマスキングは、エンコーダに入力する前の Tube マスキング（時空間的に一貫したマスク）と、デコーダを軽量に保つための Decoder マスキングの 2 段階で構成される。この設計により、より大きなモデル（ViT-g、10 億パラメータ）を実用的なGPU時間で事前学習することが可能となる。事前学習データセットとして、多様なソース（インターネット動画・映画・スポーツ等）から収集した数百万本の動画を利用する。Kinetics-400・Something-Something V2・ActivityNet などの主要な動画分類ベンチマークにおいて ViT-g が Top-1 90.0%（K400）・77.0%（SSv2）を達成し、動画理解分野での史上最高精度を更新した。",
    background: "動画理解はフレーム間の時間的依存性が高く、大規模ラベル付きデータの収集が困難だった。MAEをビジョンに適用したVideoMAEは有望だったが、ViT-Large程度のスケールに留まっており、さらに大規模なモデルへの拡張が課題だった。",
    method: "時空間Tube Maskingで高率マスキング（90%+）を実施→軽量Decoderのためさらにマスキング（Decoder Masking）を追加。ViT-g（10Bパラメータ）を数百万動画の大規模データで効率的に事前学習する。",
    results: "Kinetics-400 Top-1 90.0%、Something-Something V2 77.0%を達成し、動画理解タスクで当時のSoTAを大幅に更新。ファインチューニングなし（線形評価）でも従来の完全ファインチューニング手法に匹敵する性能を示した。",
    discussion: "動画理解分野のスケーリング則を検証した重要研究であり、大規模ビジョン基盤モデルの構築において動画の自己教師あり学習が有効であることを示した。ロボティクス・行動認識・スポーツ分析への応用が広い。",
    links: { arxiv: "https://arxiv.org/abs/2303.16727", github: "https://github.com/OpenGVLab/VideoMAEv2" }
  },
  {
    id: "florence2",
    title: "Florence-2: Advancing a Unified Representation for a Variety of Vision Tasks",
    titleJa: "Florence-2：多様な視覚タスクへの統一表現の推進",
    authors: "Bin Xiao, Haiping Wu, Weijian Xu, Xiyang Dai, Houdong Hu, Yumao Lu, Michael Zeng, Ce Liu, Lu Yuan",
    year: 2024,
    venue: "CVPR 2024",
    tags: ["Foundation Model", "Vision-Language", "マルチタスク", "物体検出"],
    summary: "本論文では、単一のプロンプトベース表現でキャプション・物体検出・セグメンテーション・視覚的接地（Grounding）など多様な視覚タスクを統一的に処理できる汎用ビジョン基盤モデル Florence-2 を提案する。大規模なデータエンジニアリングパイプラインを通じて構築した包括的な視覚アノテーションデータセット FLD-5B（5 億 4000 万の注釈付きデータポイント）を活用する。Florence-2 は画像エンコーダ（DaViT）と Transformer ベースのマルチモーダルエンコーダ・デコーダを組み合わせたシーケンス・ツー・シーケンスアーキテクチャを採用し、すべてのタスクをテキスト生成として統一的に扱う。2 億〜7 億 7000 万パラメータという比較的コンパクトなモデルサイズで、キャプション生成・物体検出・セグメンテーション・Grounding など多数のベンチマークで大規模なモデルに匹敵する性能を発揮し、特定タスク専用モデルを凌駕するゼロショット・Few-shot性能を達成した。",
    background: "視覚AIの各タスク（検出・キャプション・セグメンテーション等）はそれぞれ専用モデルが開発されてきたが、多タスクを一つのモデルで扱う統一的なアーキテクチャが求められていた。GPT系のテキスト生成アプローチをビジョンに適用する試みが活発化していた。",
    method: "FLD-5Bデータセットをテキスト生成タスクとして統一表現。画像エンコーダ（DaViT）＋マルチモーダルTransformerでテキスト・座標・マスクをシーケンスとして予測する。タスクをプロンプトで指定するPrompt-Based Multi-Task Learningを採用。",
    results: "COCO物体検出（zero-shot AP 34.7）・RefCOCO視覚的接地・キャプション・セグメンテーション等多数のベンチマークで、同等サイズのタスク専用モデルを上回る性能を達成。",
    discussion: "コンパクトながら多様なビジョンタスクを処理できるモデルとして、エッジデバイス・実用応用への展開が有望。後続の Florence-3 やMicrosoft Azure Vision APIへの統合が進んでいる。",
    links: { arxiv: "https://arxiv.org/abs/2311.06242", github: "https://github.com/microsoft/Florence-2" }
  }
];
