/**
 * 統計学実践ワークブック - 章データ
 * タイトルを変更する場合はここを編集してください。
 * ステータス管理は localStorage で行います。
 */
const CHAPTERS = [
  { num: 1,  title: "事象と確率" },
  { num: 2,  title: "確率分布と母関数" },
  { num: 3,  title: "分布の特性値" },
  { num: 4,  title: "変数変換と極限定理" },
  { num: 5,  title: "離散型確率分布" },
  { num: 6,  title: "連続型確率分布" },
  { num: 7,  title: "極限定理，漸近理論" },
  { num: 8,  title: "統計的推定の基礎" },
  { num: 9,  title: "区間推定" },
  { num: 10, title: "検定の基礎と検定法の導出" },
  { num: 11, title: "正規分布に関する検定" },
  { num: 12, title: "一般の分布に関する検定法" },
  { num: 13, title: "ノンパラメトリック法" },
  { num: 14, title: "マルコフ連鎖" },
  { num: 15, title: "確率過程の基礎" },
  { num: 16, title: "重回帰分析" },
  { num: 17, title: "回帰診断法" },
  { num: 18, title: "質的回帰" },
  { num: 19, title: "回帰分析その他" },
  { num: 20, title: "分散分析と実験計画法" },
  { num: 21, title: "標本調査法" },
  { num: 22, title: "主成分分析" },
  { num: 23, title: "判別分析" },
  { num: 24, title: "クラスター分析" },
  { num: 25, title: "因子分析・グラフィカルモデル" },
  { num: 26, title: "その他の多変量解析手法" },
  { num: 27, title: "時系列解析" },
  { num: 28, title: "分割表" },
  { num: 29, title: "不完全データの統計処理" },
  { num: 30, title: "モデル選択" },
  { num: 31, title: "ベイズ法" },
  { num: 32, title: "シミュレーション" },
  { num: 33, title: "総括――32章の全体像" },
  { num: 34, title: "模擬試験（CBT形式）" },
];
